# site title
title: Pines Cheng‘s Blog

# github user
user: Pines-Cheng 

# issue repository
repository: blog

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 554d18a7c2b7f991f91b1ebab32d498b3d91f235

# posts per page
perpage: 10


