# site title
title: Pines Cheng‘s Blog

# github user
user: Pines-Cheng 

# issue repository
repository: blog

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 4#15c377536a81a3bd9e2a9a8f0173d22e915a923

# posts per page
perpage: 10


