# site title
title: Pines Cheng‘s Blog

# github user
user: Pines-Cheng 

# issue repository
repository: blog

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 57da28d83f762bfc90ba4eed8468222c252e29d7

# posts per page
perpage: 10


